spring.application.name=HealthGrid
server.port = 8002

# DB 연결
spring.jpa.defer-datasource-initialization=true
spring.datasource.url=jdbc:mariadb://localhost:3306/healthgrid
spring.datasource.username=root
spring.datasource.password=1234

# Thymeleaf 뷰 리졸버 설정
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false # 개발 중에는 false, 운영에서는 true
spring.thymeleaf.encoding=UTF-8

# 정적 리소스 경로 설정
spring.web.resources.static-locations=classpath:/static/

# 파일 업로드(Multipart) 용량 설정
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

